USE Opiods_Staging

-- ALTER TABLE Aggregator
-- DROP COLUMN PK_Aggregator;
ALTER TABLE Aggregator
ADD PK_Aggregator INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Disaggregator
DROP COLUMN PK_Disaggregator;
ALTER TABLE Disaggregator
ADD PK_Disaggregator INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE PRUID
DROP COLUMN PK_PRUID;
ALTER TABLE PRUID
ADD PK_PRUID INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Region
DROP COLUMN PK_Region;
ALTER TABLE Region
ADD PK_Region INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Source
DROP COLUMN PK_Source;
ALTER TABLE Source
ADD PK_Source INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Specific_Measure
DROP COLUMN PK_Specific_Measure;
ALTER TABLE Specific_Measure
ADD PK_Specific_Measure INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Substance
DROP COLUMN Substance;
ALTER TABLE Substance
ADD PK_Substance INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Time_Period
DROP COLUMN PK_Aggregator;
ALTER TABLE Time_Period
ADD PK_Time_Period INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Type_Event
DROP COLUMN PK_Event;
ALTER TABLE Event
ADD PK_Event INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Unit
DROP COLUMN PK_Unit;
ALTER TABLE Unit
ADD PK_Unit INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Value
DROP COLUMN PK_Value;
ALTER TABLE Value
ADD PK_Value INT NOT NULL IDENTITY(1,1) PRIMARY KEY;

ALTER TABLE Year_Quater
DROP COLUMN PK_Year_Quater;
ALTER TABLE Year_Quater
ADD PK_Year_Quater INT NOT NULL IDENTITY(1,1) PRIMARY KEY;
